### ISSUE TITLE
Determine if we can import KMZ/KML for the BC wildfire data perimeters into Google Earth Engine

### ISSUE THREAD

**Issue by Ari1029** [rchang0501/vip-wildfire#9]
https://www.for.gov.bc.ca/ftp/HPR/external/!publish/Maps_and_Data/GoogleEarth/WMB_Fires/

Try to import the above data into google earth engine and see if it works
* If this doesn't work, try converting to .SHP file via ARCGIS or other software

**Comment by rchang0501** [comment]
found a conversion site, were able to put onto GCP
